name: Deploy to PROD

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      ENV_FILE:
        required: true
      FIREBASE_PROJECT_ID:
        required: true
      FIREBASE_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Populate env file
        run: |
          echo "${{ secrets.ENV_FILE_DEV }}" > .env
          if ! grep -q VITE_PROJECT_ID .env; then
            echo "::error:: The .env file is likely not populated correctly"
            exit 1
          fi

      - name: Build
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          npm ci
          npm --prefix functions ci functions
          npm run build
      - name: Deploy PROD
        run: |
          npm install -g firebase-tools
          firebase deploy --project="${{ secrets.FIREBASE_PROJECT_ID }}" --token="${{ secrets.FIREBASE_TOKEN }}"
