name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: |
            ~/cache
            !~/cache/exclude
            **/node_modules
            ~/.cache
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: |
          npm ci
          npm --prefix functions ci functions
        env:
          CI: true

      - name: npm lint
        run: |
          npm run lint
          npm run lint:style

      - name: npm test:unit
        run: |
          npm run test:unit
        env:
          CI: true
