name: "OpenAPI validation"

on:
  push:
    branches: [main]
    paths:
      - public/openapi.yaml
  pull_request:
    branches: [main]
    paths:
      - public/openapi.yaml
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: OpenAPI definition validation

    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@65266f9d3147e446b96af879fd317ce6079529ea # v1.3.2
        with:
          definition-file: public/openapi.yaml
